symlinks = [
  ".config/sway",
  ".config/nvim",
  ".config/wallpaper",
  ".config/systemd/user/googledrive.service",
  ".config/systemd/user/onedrive.service",
  ".config/systemd/user/wallpaper.service",
  ".config/mpv",
  ".config/ferium/config.json",
  ".zshrc",
  ".zimrc",
  "screenshot.sh",
  ".zprofile",
  ".config/wezterm",
]
